set nocompatible              " be iMproved, required
filetype off                  " required

" ================ General Config ====================
"
set number                      "Line numbers are good
set backspace=indent,eol,start  "Allow backspace in insert mode
set history=1000                "Store lots of :cmdline history
set showcmd                     "Show incomplete cmds down the bottom
set showmode                    "Show current mode down the bottom
set gcr=a:blinkon0              "Disable cursor blink
set visualbell                  "No sounds
set autoread                    "Reload files changed outside vim
set cursorline

" This makes vim act like all other editors, buffers can
" exist in the background without being in a window.
" http://items.sjbach.com/319/configuring-vim-right
set hidden

" =============== Vim Plug Initialization ===============
" " This loads all the plugins specified in ~/.vim/plug.vim
if filereadable(expand("~/.vim/plug.vim"))
  source ~/.vim/plug.vim
endif

" ================ Turn Off Swap Files ==============
"
set noswapfile
set nobackup
set nowb

" ================ Indentation ======================
"
set autoindent
set smartindent
set smarttab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab

filetype plugin on
filetype indent on


" Display tabs and trailing spaces visually
" set list listchars=tab:\ \ ,trail:·
"
set nowrap       "Don't wrap lines
set linebreak    "Wrap lines at convenient points

" ================ Scrolling ========================
"
set scrolloff=8         "Start scrolling when we're 8 lines away from margins
set sidescrolloff=15
set sidescroll=1
set foldlevel=99

nnoremap <silent> \t :NERDTree<CR>
nnoremap <silent> \T :NERDTreeFind<CR>
nnoremap <silent> ,i :JavaImport<CR>
nnoremap <silent> ,i :JavaImport<CR>

syntax enable
set background=dark
colorscheme hybrid
" colorscheme iceberg
" colorscheme nord
" colorscheme stellarized_dark
" let g:solarized_termcolors=256
set clipboard=unnamed,unnamedplus

"
" If you have vim >=8.0 or Neovim >= 0.1.5
if (has("termguicolors"))
 set termguicolors
endif

" For Neovim 0.1.3 and 0.1.4
" let $NVIM_TUI_ENABLE_TRUE_COLOR=1



so ~/.vim/settings.vim

autocmd Filetype html setlocal ts=2 sts=2 sw=2
autocmd Filetype vue setlocal ts=2 sts=2 sw=2
autocmd Filetype ruby setlocal ts=2 sts=2 sw=2
autocmd Filetype javascript setlocal ts=2 sts=2 sw=2

autocmd Filetype typescript set softtabstop=2
autocmd Filetype typescript set sw=2
autocmd Filetype typescript set ts=2

set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.class,*/target/*,*/node_modules/*,*/bower_components/*
set wildignore+=*/dist/*

"let g:EclimCompletionMethod = 'omnifunc'
"
"if !exists('g:neocomplcache_force_omni_patterns')
"    let g:neocomplcache_force_omni_patterns = {}
"endif
"let g:neocomplcache_force_omni_patterns.java = '\k\.\k*'
"let g:neocomplcache_force_omni_patterns.scala = '\k\.\k*'
