#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
for config_file (~/dev/dotfiles/zsh/*.zsh) source $config_file

if [[ -s "$HOME/.rbenv" ]]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi

# added by travis gem
[ -f /home/verto/.travis/travis.sh ] && source /home/verto/.travis/travis.sh

#tmux attach &> /dev/null

#if [[ ! $TERM =~ screen ]]; then
#    exec tmux
#fi
#
export SCALA_HOME=/home/verto/dev/scala
export VIM_HOME=/home/verto/dev/vim
export JAVA_HOME=/home/verto/dev/jdk1.8.0_161
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export PATH=$VIM_HOME/bin:$PATH:$SCALA_HOME/bin:$JAVA_HOME/bin
export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin:$HOME/dev/jet
export GOPATH=/home/verto/dev/projects/go
export VERTO_SCRIPTS=/home/verto/dev/apps
export PASS_HOME=/home/verto/dev/op
export CARGO_BIN=/home/verto/.cargo/bin
export FLUTTER_DIR=/home/verto/dev/flutter/flutter

export PATH=$PATH:$GOPATH/bin:$PASS_HOME:$CARGO_BIN:$VERTO_SCRIPTS:$FLUTTER_DIR/bin
export DASHT_DOCSETS_DIR=~/.local/share/Zeal/Zeal/docsets

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
